# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
  # Tăng versionCode và versionName theo thời gian thực
    version_code = Time.now.to_i # → ví dụ: 1721859558
    version_name = "1.0.#{Time.now.strftime('%Y%m%d')}"

    gradle(
        task: "clean bundleRelease",
        properties: {
          "VERSION_CODE" => version_code,
          "VERSION_NAME" => version_name
        }
    )
    # build_info_path = File.expand_path("../build_info.env", __dir__)
    build_info_path = File.expand_path("../../build_info.env", __dir__)
    File.write(build_info_path, <<~ENV)
      VERSION_CODE=#{version_code}
      VERSION_NAME=#{version_name}
    ENV
  # Đẩy lên Google Play
    upload_to_play_store(
      track: "internal",
      json_key: "./playstore_credentials.json",
      package_name: "com.haonguyen.mynewapp",
      release_status: "draft"
    )
  end

end
