# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
      gradle_file = "app/build.gradle"

  current_code = android_get_version_code(gradle_file: gradle_file).to_i
  current_name = android_get_version_name(gradle_file: gradle_file)

  # Tăng versionCode
  android_set_version_code(
    version_code: current_code + 1,
    gradle_file: gradle_file
  )

  # Tăng versionName x.y.z => x.y.(z+1)
  components = current_name.split(".").map(&:to_i)
  components[-1] += 1
  new_name = components.join(".")

  android_set_version_name(
    version_name: new_name,
    gradle_file: gradle_file
  )
    gradle(task: "clean bundleRelease")
     upload_to_play_store(
        track: "internal",
        json_key: "./playstore_credentials.json",
        package_name: "com.haonguyen.mynewapp",
        release_status: "draft"
      )
  end
end
